[package]
name = "sofa"
version = "0.5.0"
authors = ["Mathieu Amiot <m.amiot@otak-arts.com>"]

[dependencies]
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.10"
reqwest = "0.8.5"

[dev-dependencies]
pretty_assertions = "0.5"
