[package]
name = "sofa"
version = "0.5.1"
authors = ["Mathieu Amiot <mathieu.amiot@yellowinnovation.fr>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.8"

[dev-dependencies]
pretty_assertions = "0.5"
