[package]
name = "sofa"
version = "0.7.0"
authors = ["Mathieu Amiot <mathieu.amiot@yellowinnovation.fr>", "mibes <mibes@mibesco.com>"]
license = "MIT/Apache-2.0"
description = "Sofa - CouchDB for Rust"
readme = "README.md"
documentation = "https://docs.rs/sofa"
homepage = "https://github.com/YellowInnovation/sofa"
repository = "https://github.com/YellowInnovation/sofa"
keywords = ["couchdb", "orm", "database", "nosql"]
categories = ["database"]
edition = "2018"
include = [
    "**/*.rs",
    "Cargo.toml"
]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.45"
url = "2.1.1"
tokio = { version = "0.2.11", features = ["full"] }
async-trait = "0.1.24"

[dependencies.reqwest]
version = "0.10.1"
features = ["json", "gzip", "cookies", "blocking"]

[dev-dependencies]
pretty_assertions = "0.5"
tokio = { version = "0.2.11", features = ["full"] }
