[package]
name = "sofa"
version = "0.4.0"
authors = ["Mathieu Amiot <m.amiot@otak-arts.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.8"
url = "1.6"
maplit = "1.0"

[dev-dependencies]
pretty_assertions = "0.5"
